### ISSUE TITLE
Problems with letters in the Ukrainian translation

### ISSUE THREAD

**Issue by Andrew1397** [namidaco/namida-translations#43]
Letters such as "ґ", "ї", "і", "є" are replaced by the symbols shown in the photo. 
For example, I added all the problematic letters in the following line
![зображення](https://github.com/namidaco/namida-translations/assets/44724275/b267d453-8a79-4b69-9a82-f2acd843441e)
And this is how they appear in the program (You can also see these letters in words that are replaced by symbols)
![Screenshot_20240503-115524_Namida](https://github.com/namidaco/namida-translations/assets/44724275/fbe6b35b-01e5-4cee-94de-c94c7bfeea84)

**Comment by VerySweetBread** [comment]
https://github.com/namidaco/namida-translations/pull/38#issuecomment-2040646835

**Comment by MSOB7YY** [comment]
@VerySweetBread @Andrew1397 this is rather an app problem, not translation, gonna close this and keep https://github.com/namidaco/namida/issues/183?notification_referrer_id=NT_kwDOBRS8l7QxMDUxMjQyMjE4NTo4NTI0NTA3OQ#issuecomment-2092698570

**Comment by VerySweetBread** [comment]
> @VerySweetBread @Andrew1397 this is rather an app problem, not translation, gonna close this and keep https://github.com/namidaco/namida/issues/183?notification_referrer_id=NT_kwDOBRS8l7QxMDUxMjQyMjE4NTo4NTI0NTA3OQ#issuecomment-2092698570

Makes sense, sorry
